CREATE TABLE PARENT_TASK
(
ID INT(10) PRIMARY KEY,
TASK VARCHAR(100)
);


CREATE TABLE TASK
(
ID INT(15) PRIMARY KEY AUTO_INCREMENT,
TASK VARCHAR(100),
START_DATE DATE,
END_DATE DATE,
PRIORITY INT(2),
PARENT_TASK_ID INT(10),
FOREIGN KEY(PARENT_TASK_ID) REFERENCES PARENT_TASK (ID)
);

CREATE TABLE USER
(
ID INT(15) PRIMARY KEY AUTO_INCREMENT,
EMPLOYEE_ID INT(15) UNIQUE NOT NULL,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL
);